apiVersion: apps/v1
kind: Deployment
metadata:
  name: centosapp
  labels:
    app: centos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos
  template:
    metadata:
      labels:
        app: centos
    spec:
      containers:
      - name: centoscont
        image: centos:7
        command: ["/bin/bash", "-c", "sleep 10000"]
        volumeMounts:
          - name: my-pv
            mountPath: "/tmp/persistent"
      volumes:
      - name: my-pv
        persistentVolumeClaim:
          claimName: my-pvc
