version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "80:80"
    volumes:
      - ./ngnix.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend1
      - backend2
      - backend3
  backend1:
    build: .
    container_name: backend1
    expose:
      - 5000
  backend2:
    build: .
    container_name: backend2
    expose:
      - "5001"
  backend3:
    build: .
    container_name: backend3
    expose:
      - "5002"
