apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ib-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ib-banking
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20
