apiVersion: batch/v1
kind: CornJob
metadata:
  name: cornjob
  labels:
    app: cornjob
spec:
  schedule: "*/1 * * * *"
  template:
    metadata:
      labels:
        app: cornjob
    spec:
      conatiners:
        - name: busybox
          image: busybox
          command: ["sh","-c","echo hello from cornJob && sleep 10"]
      restartPolicy: Never
