apiVersion: batch/v1
kind: Job
metadata:
  name: nonparalleljob
  labels:
    app: nonparallel
spec:
  completions: 3
  template:
    metadata:
      labels:
        app: nonparallel
    spec:
      restartPolicy: Never
      containers:
        - name: busyboxcont
          image: busyboxcont
          command: ["sh","-c","echo hello from busybox && sleep 10"]
