apiVersion: v1
kind: Pod
metadata:
  name: two-container-pod
  labels:
    app: multi-container
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80

    - name: busybox-container
      image: busybox
      command: ["sh", "-c", "while true; do echo Hello from BusyBox; sleep 5; done"]
